email:
  enabled: true
  smtp_host: "live.smtp.mailtrap.io"
  smtp_port: 587
  username: "api"
  password_env: "MAILTRAP_TOKEN"
  from: "rfp@thinkelearn.com"
  to: "f.villegas@thinkelearn.com"

llm:
  enabled: false
  enabled_env: "LLM_ENABLED"  # set to 0/false/off to force-disable, 1/true/on to force-enable
  api_key_env: "OPENAI_API_KEY"
  model: "gpt-5-nano"
  rationale: true  # include a short reason when LLM filtering is enabled

sources:
  - name: "CharityVillage RFPs"
    url: "https://www.charityvillage.com/jobs/request-proposal/canada"
    include_keywords: ["request for proposal", "rfp"]
    exclude_keywords: []

  - name: "Bids&Tenders Portal"
    url: "https://www.bidsandtenders.com/bid-opportunities/"
    include_keywords: ["request for proposal", "tender", "bid"]
    exclude_keywords: ["login", "vendor", "support", "guide", "mailto"]

  - name: "CanadaBuys – Tender Opportunities"
    url: "https://canadabuys.canada.ca/en/tender-opportunities"
    include_keywords: ["request for proposal", "call for proposals", "rfp", "tender"]
    exclude_keywords: ["#wb", "#", "request-contract-history-letter", "chat", "page="]

  - name: "MERX"
    url: "https://www.merx.com/public/solicitations/open?publishDate=HOURS_24"
    include_keywords: ["request for proposal", "rfp", "tender"]
    exclude_keywords: ["twitter", "login", "resources", "guide", "mailto"]

  - name: "United Way Halton & Hamilton – Feed/Seed Grants"
    url: "https://uwhh.ca/granting/"
    include_keywords: ["grant", "application", "call for proposals", "request for proposals", "rfp", "funding"]
    exclude_keywords: []

  - name: "United Way Halton & Hamilton – Feed Grant"
    url: "https://uwhh.ca/granting/feed-grant/"
    include_keywords: ["grant", "application", "call for proposals", "request for proposals", "rfp", "funding"]
    exclude_keywords: []

  - name: "United Way Halton & Hamilton – Seed Grant"
    url: "https://uwhh.ca/granting/seed-grant/"
    include_keywords: ["grant", "application", "call for proposals", "request for proposals", "rfp", "funding"]
    exclude_keywords: []

  - name: "United Way KFLA – Funding"
    url: "https://www.unitedwaykfla.ca/funding/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "United Way East Ontario – Funding/CFPs"
    url: "https://www.unitedwayeo.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "Vantage Point / BC Nonprofit Network"
    url: "https://thevantagepoint.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "Ontario Nonprofit Network"
    url: "https://theonn.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "procurement"]
    exclude_keywords: []

  - name: "Imagine Canada"
    url: "https://www.imaginecanada.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "grant"]
    exclude_keywords: []

  - name: "TechSoup Canada"
    url: "https://www.techsoup.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "CCVO / The Nonprofit Chamber"
    url: "https://www.thenonprofitchamber.org/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "United Way Simcoe Muskoka"
    url: "https://uwsimcoemuskoka.ca/rhinformationpage/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "United Way Greater Toronto"
    url: "https://www.unitedwaygt.org/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "funding"]
    exclude_keywords: []

  - name: "United Way British Columbia"
    url: "https://uwbc.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "funding"]
    exclude_keywords: []

  - name: "United Way Calgary & Area"
    url: "https://calgaryunitedway.org/"
    include_keywords: ["call for proposals", "request for proposals", "rfp"]
    exclude_keywords: []

  - name: "Vancouver Foundation"
    url: "https://www.vancouverfoundation.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "grant"]
    exclude_keywords: []

  - name: "Toronto Foundation"
    url: "https://torontofoundation.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "grant"]
    exclude_keywords: []

  - name: "Hamilton Community Foundation"
    url: "https://www.hamiltoncommunityfoundation.ca/"
    include_keywords: ["call for proposals", "request for proposals", "rfp", "grant"]
    exclude_keywords: []

  - name: "City of Toronto – Tenders"
    url: "https://www.toronto.ca/business-economy/doing-business-with-the-city/current-possible-opportunities/"
    include_keywords: ["request for proposal", "rfp", "tender"]
    exclude_keywords: []

  - name: "City of Hamilton – Bids & Tenders"
    url: "https://www.hamilton.ca/city-council/bids-tenders"
    include_keywords: ["request for proposal", "rfp", "tender"]
    exclude_keywords: []

  - name: "City of Burlington – Bids & Tenders"
    url: "https://burlington.bidsandtenders.ca/Module/Tenders/en"
    include_keywords: ["request for proposal", "rfp", "tender", "bid"]
    exclude_keywords: []

  - name: "Halton Region – Bids & Tenders"
    url: "https://haltonregion.bidsandtenders.ca/Module/Tenders/en"
    include_keywords: ["request for proposal", "rfp", "tender", "bid"]
    exclude_keywords: []

  - name: "Region of Waterloo – Bids & Tenders"
    url: "https://www.regionofwaterloo.ca/en/resources/bids-and-tenders.aspx"
    include_keywords: ["request for proposal", "rfp", "tender"]
    exclude_keywords: []
